#!/usr/bin/env bun
/**
 * Schema-to-PureScript Type & Decoder Generator (inspired by IHP Schema Codegen).
 *
 * Reads PostgreSQL DDL / migration files and generates type-safe PureScript domain
 * records, Argonaute JSON decoders/encoders, and SQL row mappings.
 *
 * Usage:
 *   bun scripts/gen-sql.js migrations/001_initial.sql
 *   bun scripts/gen-sql.js --file=migrations/001_initial.sql --table=comments --out=src/App/Features/Comments/Types.purs
 *   bun scripts/gen-sql.js --sql="CREATE TABLE comments (id SERIAL PRIMARY KEY, post_id INT NOT NULL, author TEXT NOT NULL, body TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL);"
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";

function toCamelCase(str) {
  return str.replace(/_([a-z0-9])/g, (_, g) => g.toUpperCase());
}

function toPascalCase(str) {
  const camel = toCamelCase(str);
  return camel.charAt(0).toUpperCase() + camel.slice(1);
}

function mapSqlTypeToPureScript(sqlType, isNullable) {
  const normalized = sqlType.toUpperCase().trim();
  let psType = "String";

  if (/^(INT|INTEGER|SERIAL|BIGINT|SMALLINT)/.test(normalized)) {
    psType = "Int";
  } else if (/^(NUMERIC|DECIMAL|REAL|FLOAT|DOUBLE)/.test(normalized)) {
    psType = "Number";
  } else if (/^(BOOL|BOOLEAN)/.test(normalized)) {
    psType = "Boolean";
  } else if (/^(JSON|JSONB)/.test(normalized)) {
    psType = "Json";
  } else if (/^(TEXT|VARCHAR|CHAR|UUID|TIMESTAMPTZ|TIMESTAMP|DATE|TIME)/.test(normalized)) {
    psType = "String";
  }

  if (isNullable) {
    return `Maybe ${psType}`;
  }
  return psType;
}

function parseSql(sql) {
  const tables = [];
  const tableRegex = /CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?([a-zA-Z0-9_"]+)\s*\(([\s\S]*?)\);/gi;
  let match;

  while ((match = tableRegex.exec(sql)) !== null) {
    const rawTableName = match[1].replace(/"/g, "");
    const body = match[2];
    const columns = [];

    // Split columns by comma, respecting parentheses
    const columnDefs = [];
    let current = "";
    let depth = 0;
    for (let i = 0; i < body.length; i++) {
      const char = body[i];
      if (char === "(") depth++;
      else if (char === ")") depth--;
      else if (char === "," && depth === 0) {
        columnDefs.push(current.trim());
        current = "";
        continue;
      }
      current += char;
    }
    if (current.trim()) columnDefs.push(current.trim());

    for (const line of columnDefs) {
      if (!line || /^(PRIMARY\s+KEY|FOREIGN\s+KEY|CONSTRAINT|UNIQUE|CHECK)/i.test(line)) {
        continue;
      }

      const colMatch = line.match(/^([a-zA-Z0-9_"]+)\s+([a-zA-Z0-9_()]+)([\s\S]*)$/);
      if (colMatch) {
        const colName = colMatch[1].replace(/"/g, "");
        const sqlType = colMatch[2];
        const rest = colMatch[3] || "";
        const isNotNull = /NOT\s+NULL/i.test(rest) || /PRIMARY\s+KEY/i.test(rest);
        const isNullable = !isNotNull;
        columns.push({
          name: colName,
          camelName: toCamelCase(colName),
          sqlType,
          psType: mapSqlTypeToPureScript(sqlType, isNullable),
          isNullable,
        });
      }
    }

    if (columns.length > 0) {
      tables.push({
        name: rawTableName,
        pascalName: toPascalCase(rawTableName.replace(/s$/, "")),
        columns,
      });
    }
  }

  return tables;
}

function generatePureScriptModule(table, moduleName) {
  const { pascalName, columns } = table;
  const hasMaybe = columns.some((c) => c.isNullable);
  const hasJson = columns.some((c) => c.psType === "Json" || c.psType === "Maybe Json");

  const maybeImport = hasMaybe ? "\nimport Data.Maybe (Maybe(..))" : "";
  const jsonImport = hasJson ? "\nimport Data.Argonaut.Core (Json)" : "";

  const recordFields = columns
    .map((c) => `  , ${c.camelName} :: ${c.psType}`)
    .join("\n")
    .replace(/^  ,/, "  {");

  const decodeFields = columns
    .map((c) => {
      const op = c.isNullable ? ".:?" : ".:";
      return `    ${c.camelName} <- obj ${op} "${c.name}"`;
    })
    .join("\n");

  const encodeFields = columns
    .map((c) => {
      const op = c.isNullable ? ":=?" : ":=";
      return `    "${c.name}" ${op} val.${c.camelName}`;
    })
    .join("\n    ~> ");

  return `-- | Generated domain types and JSON codecs for table \`${table.name}\`.
-- | Auto-generated by \`make gen-sql\` (Pohjola Schema Codegen).
module ${moduleName}
  ( ${pascalName}(..)
  , ${pascalName}Row
  ) where

import Prelude
${maybeImport}${jsonImport}
import Data.Argonaut.Decode (class DecodeJson, decodeJson, (.:), (.:?))
import Data.Argonaut.Decode.Error (JsonDecodeError(..))
import Data.Argonaut.Encode (class EncodeJson, (:=), (:=?), (~>), jsonEmptyObject)
import Data.Either (Either(..))
import Data.Newtype (class Newtype, unwrap)

type ${pascalName}Row =
${recordFields}
  }

newtype ${pascalName} = ${pascalName} ${pascalName}Row

derive instance newtype${pascalName} :: Newtype ${pascalName} _
derive newtype instance eq${pascalName} :: Eq ${pascalName}
derive newtype instance show${pascalName} :: Show ${pascalName}

instance decodeJson${pascalName} :: DecodeJson ${pascalName} where
  decodeJson json = do
    obj <- decodeJson json
${decodeFields}
    pure (${pascalName}
      { ${columns.map((c) => `${c.camelName}`).join("\n      , ")}
      })

instance encodeJson${pascalName} :: EncodeJson ${pascalName} where
  encodeJson (${pascalName} val) =
${encodeFields}
    ~> jsonEmptyObject
`;
}

// --- CLI Runner -------------------------------------------------------------
const args = process.argv.slice(2);
let sqlInput = "";
let targetTable = "";
let outPath = "";
let moduleNameOverride = "";

for (const arg of args) {
  if (arg.startsWith("--file=")) {
    sqlInput = readFileSync(arg.slice(7), "utf-8");
  } else if (arg.startsWith("--sql=")) {
    sqlInput = arg.slice(6);
  } else if (arg.startsWith("--table=")) {
    targetTable = arg.slice(8);
  } else if (arg.startsWith("--out=")) {
    outPath = arg.slice(6);
  } else if (arg.startsWith("--module=")) {
    moduleNameOverride = arg.slice(9);
  } else if (!arg.startsWith("--") && !sqlInput) {
    sqlInput = readFileSync(arg, "utf-8");
  }
}

if (!sqlInput) {
  // Default: scan migrations directory if present
  try {
    const files = (await import("node:fs")).readdirSync("migrations").sort();
    sqlInput = files.map((f) => readFileSync(`migrations/${f}`, "utf-8")).join("\n\n");
  } catch {
    console.error("Usage: bun scripts/gen-sql.js <path-to-sql-file> [--table=<name>] [--out=<path>]");
    process.exit(1);
  }
}

const tables = parseSql(sqlInput);

if (tables.length === 0) {
  console.log("No CREATE TABLE statements found in SQL input.");
  process.exit(0);
}

for (const table of tables) {
  if (targetTable && table.name.toLowerCase() !== targetTable.toLowerCase()) {
    continue;
  }

  const modName = moduleNameOverride || `App.Features.${table.pascalName}.Types`;
  const code = generatePureScriptModule(table, modName);

  if (outPath) {
    mkdirSync(dirname(outPath), { recursive: true });
    writeFileSync(outPath, code, "utf-8");
    console.log(`✓ Generated ${outPath} for table '${table.name}'`);
  } else {
    console.log(`\n-- ==================== Table: ${table.name} ====================`);
    console.log(code);
  }
}
